config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#home"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "logout" => "user_sessions#destroy", :as => :logout
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :review_requests, only: [:index, :new, :create]
  resources :groups do
    resources :group_members, only: [:create, :destroy], as: :members
  end
  resources :group_member_forms, only: [:create, :destroy]
  resources :users do
    resource :activate, only: [:create, :destroy], module: :users
  end
  resource :fetch_mattermost_id, only: [:create], module: :users
  resource :join_groups, only: [:new, :create, :destroy]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # NOTE: current_userで取得したユーザーのみを対象とするため、authorizeメソッドをスキップする
  skip_after_action :verify_authorized, only: %i[show edit update destroy]

  def show; end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    @user.assign_attributes(user_params)
    if @user.save(context: :account_setup)
      redirect_to profile_path, notice: 'プロフィールを更新しました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_user.destroy!
    redirect_to root_path, notice: 'アカウントを削除しました。'
  end

  private

  def user_params
    params.require(:user).permit(:nickname)
  end
end

app/views/profiles/_mattermost_modal.html.erb
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">MattermostID取得</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: fetch_mattermost_id_path do |f| %>
          <div class="mb-3">
            <%= f.label :email, 'メールアドレス', class: "form-label" %>
            <%= f.text_field :email, class: "form-control" %>
            <p class="form-text text-muted">Mattermostのメールアドレスを入力してください</p>
          </div>
          <div class="mb-3">
            <%= f.label :password, 'パスワード', class: "form-label" %>
            <%= f.password_field :password, class: "form-control" %>
            <p class="form-text text-muted">Mattermostのパスワードを入力してください</p>
          </div>
          <%= f.submit 'IDを取得', class: "btn btn-primary", data: { bs_dismiss: "modal" } %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_unsubscribe_modal.html.erb
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">アカウント削除</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h5>アカウント削除をすると、以下の情報が削除されます</h2>
        <ul>
          <li>ユーザー情報</li>
          <li>依頼したレビュー情報</li>
          <li>依頼されたレビュー情報</li>
        </ul>
        <%= link_to "削除する", profile_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<%= render 'mattermost_modal' %>
<section>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3 py-3">
          <div class="row g-0">
            <div class="col-md-4 text-center my-auto">
              <h1 class=""><i class="bi bi-github"></i></h1>
              <p><%= current_user.github_id %></p>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h5 class="mb-0">プロフィール</h5>
                </div>
                <hr class="mt-0 mb-4">
                <%= form_with model: @user, url: profile_path do |f| %>
                  <% if @user.errors.any? %>
                    <div class="alert alert-danger mt-2" role="alert">
                      <ul class="mb-0 list-inline">
                        <% @user.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <div class="row pt-1">
                    <div class="mb-3">
                      <%= f.label :nickname, class: "form-label" do %>
                        <%= User.human_attribute_name(:nickname) %>
                        <span class="text-danger">*</span>
                      <% end %>
                      <%= f.text_field :nickname, class: "form-control" %>
                    </div>
                  </div>
                  <div class="row pt-1">
                    <div class="mb-3">
                      <div class="d-flex mb-2 align-items-center">
                        <p class="form-label my-auto"><%= User.human_attribute_name(:mattermost_id) %></p>
                        <span class="text-danger ms-1">*</span>
                        <button type="button" class="btn btn-success btn-sm ms-1" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                          IDを取得
                        </button>
                      </div>
                      <%= f.text_field :mattermost_id, class: "form-control bg-secondary-subtle", readonly: true %>
                      <div class="form-text text-muted">IDを取得でMattermostのIDを取得してください</div>
                    </div>
                  </div>
                  <%= f.submit nil, class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/profiles/show.html.erb
<%= render 'unsubscribe_modal' %>
<section>
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3 py-3">
          <div class="row g-0">
            <div class="col-md-4 text-center my-auto">
              <h1 class=""><i class="bi bi-github"></i></h1>
              <p><%= current_user.github_id %></p>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  <h5 class="mb-0">プロフィール</h5>
                  <%= link_to edit_profile_path, class: "text-decoration-none" do %>
                    <i class="bi bi-pencil-square h4"></i>
                  <% end %>
                </div>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  <div class="mb-3">
                    <h6 class="h5"><%= User.human_attribute_name(:nickname) %></h6>
                    <p class="text-muted"><%= current_user.nickname || '設定されていません' %></p>
                  </div>
                </div>
                <div class="row pt-1">
                  <div class="mb-3">
                    <h6 class="h5"><%= User.human_attribute_name(:mattermost_id) %></h6>
                    <p class="text-muted"><%= current_user.mattermost_id || '設定されていません' %></p>
                  </div>
                </div>
                <div class="row pt-1">
                  <div class="mb-3">
                    <h6 class="h5"><%= User.human_attribute_name(:activated) %></h6>
                    <p class="text-muted"><%= current_user.activated? ? 'アクティベート済み' : 'アクティベーション待ち' %></p>
                  </div>
                </div>
                <div class="row pt-1">
                  <div class="mb-3">
                    <div class="d-flex">
                      <h6 class="h5">所属グループ</h6>
                      <%= link_to new_join_groups_path, class: 'ms-3' do %>
                        <i class="bi bi-plus-square h4"></i>
                      <% end %>
                    </div>
                    <ul class="list-unstyled" id="new_join_group_list"></ul>
                    <ul class="list-unstyled">
                      <% current_user.groups.each do |group| %>
                        <li><%= group.name %></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
                <div class="pt-1">
                  <%= link_to 'アカウント削除方法はこちら', nil, data: { bs_toggle: "modal", bs_target: "#staticBackdrop" } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>