config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#home"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "logout" => "user_sessions#destroy", :as => :logout
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :review_requests, only: [:index, :new, :create]
  resources :groups do
    resources :group_members, only: [:create, :destroy], as: :members
  end
  resources :group_member_forms, only: [:create, :destroy]
  resources :users do
    resource :activate, only: [:create, :destroy], module: :users
  end
  resource :fetch_mattermost_id, only: [:create], module: :users
  resource :join_groups, only: [:new, :create, :destroy]
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :mattermost_channel_id, presence: true

  has_many :group_members, dependent: :destroy
  has_many :users, through: :group_members

  def added_at(user)
    group_members.find_by(user:).created_at
  end

  def user_order_by_reviewer_amount(reviewee_id)
    users.where.not(id: reviewee_id)
         .joins('LEFT JOIN review_requests ON review_requests.reviewer_id=users.id')
         .group(:id).order('count(review_requests.id)').first
  end

  def joined?(user)
    users.include?(user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
    authorize @groups
  end

  def new
    @group = Group.new
    authorize @group
  end

  def edit
    @group = Group.find(params[:id])
    authorize @group
  end

  def create
    @group = Group.new
    authorize @group
    @group_form = GroupForm.new(group_params)
    if @group_form.save
      redirect_to groups_path
    else
      flash.now[:alert] = @group_form.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @group = Group.find(params[:id])
    authorize @group
    @group_form = GroupForm.new(group_params.merge(group: @group))
    if @group_form.update
      redirect_to groups_path
    else
      flash.now[:alert] = @group_form.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :mattermost_channel_id).merge(group_member_ids: params[:group_member_ids])
  end
end

app/views/groups/edit.html.erb
<div class="container w-50 p-2">
  <div class="d-flex align-items-center justify-content-between">
    <h1>グループ編集</h1>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= form_with model: @group do |f| %>
            <div class="form-group mb-2">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :mattermost_channel_id %>
              <%= f.text_field :mattermost_channel_id, class: "form-control" %>
            </div>
            <div class="form-group" id="group_members_field" data-controller="group_member">
              <div class="d-flex align-items-center position-relative">
                <p class="form-label">メンバー追加</p>
                <%= link_to group_member_forms_path(group_id: @group), class: 'stretched-link', data: { turbo_method: :post } do %>
                  <i class="bi bi-person-fill-add h5 ms-3"></i>
                <% end %>
              </div>
              <% @group.group_members.each do |group_member| %>
                <%= render 'group_member_forms/group_member_fields', group_member: group_member %>
              <% end %>
            </div>
            <div class="form-group">
              <%= f.submit nil, class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container w-50 p-2">
  <div class="d-flex align-items-center justify-content-between">
    <h1>グループ一覧</h1>
    <%= link_to 'グループを追加', new_group_path, class: 'btn btn-primary' %>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <% @groups.each do |group| %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex align-items-center justify-content-between mb-2">
              <h5 class="card-title mb-0"><%= group.name %></h5>
              <%= link_to edit_group_path(group) do %>
                <i class="bi bi-pencil h4 text-success"></i>
              <% end %>
            </div>
            <p class="card-text">channel_id: <%= group.mattermost_channel_id.presence || 'チャンネルIDが設定されていません' %></p>
          </div>
          <div class="card-body text-center">
            <%= form_with url: group_members_path(group), class: "row" do |f| %>
              <div class="col-8">
                <%= f.collection_select :user_id, User.all, :id, :nickname, { include_blank: '追加したいメンバーを選択' }, class: 'form-select' %>
              </div>
              <div class="col-4">
                <%= f.submit '追加', class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="table">
              <table class="table no-wrap mb-0">
                <thead>
                  <tr>
                    <th scope="col" class="border-0 text-uppercase font-medium">メンバー名</th>
                    <th scope="col" class="border-0 text-uppercase font-medium">グループ追加日</th>
                    <th scope="col" class="border-0"></th>
                  </tr>
                </thead>
                <tbody>
                  <% group.users.each do |user| %>
                    <tr>
                      <td>
                        <span class="font-medium mb-0"><%= user.nickname || '設定されていません' %></h5>
                      </td>
                      <td>
                        <span class="text-muted"><%= strfdate(group.added_at(user)) %></span>
                      </td>
                      <td>
                        <%= link_to group_member_path(group, user), data: { turbo_method: :delete, turbo_confirm: 'グループから外しますか？' } do %>
                          <i class="bi bi-file-minus h4 text-danger"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container w-50 p-2">
  <div class="d-flex align-items-center justify-content-between">
    <h1>グループ新規作成</h1>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
          <%= form_with model: @group do |f| %>
            <div class="form-group mb-2">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group mb-2">
              <%= f.label :mattermost_channel_id %>
              <%= f.text_field :mattermost_channel_id, class: "form-control" %>
            </div>
            <div class="form-group" id="group_members_field" data-controller="group_member">
              <div class="d-flex align-items-center position-relative">
                <p class="form-label">メンバー追加</p>
                <%= link_to group_member_forms_path(group_id: @group), class: 'stretched-link', data: { turbo_method: :post } do %>
                  <i class="bi bi-person-fill-add h5 ms-3"></i>
                <% end %>
              </div>
            </div>
            <div class="form-group">
              <%= f.submit nil, class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>