config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#home"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "logout" => "user_sessions#destroy", :as => :logout
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :review_requests, only: [:index, :new, :create]
  resources :groups do
    resources :group_members, only: [:create, :destroy], as: :members
  end
  resources :group_member_forms, only: [:create, :destroy]
  resources :users do
    resource :activate, only: [:create, :destroy], module: :users
  end
  resource :fetch_mattermost_id, only: [:create], module: :users
  resource :join_groups, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  enum role: { general: 0, admin: 1 }

  validates :nickname, presence: true, on: :account_setup
  validates :mattermost_id, presence: true, on: :account_setup

  has_many :review_requests, dependent: :destroy, foreign_key: :reviewee_id, class_name: 'ReviewRequest',
                             inverse_of: :reviewee
  has_many :reviewer_requests, dependent: :destroy, foreign_key: :reviewer_id, class_name: 'ReviewRequest',
                               inverse_of: :reviewer
  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members

  scope :activated, -> { where(activated: true) }
  scope :prioritize_unjoined_group, -> { left_joins(:group_members).group(:id).order('COUNT(group_members.id) ASC') }

  def profile_setup?
    nickname.present? && mattermost_id.present?
  end

  def joined_any_group?
    groups.present?
  end

  def joined_multiple_groups?
    groups.count > 1
  end

  def group
    groups&.sample
  end

  def activate!
    update!(activated: true)
  end
end

app/controllers/users/activates_controller.rb
module Users
  class ActivatesController < ApplicationController
    def create
      user = User.find(params[:user_id])
      authorize(user, :update?)
      user.update(activated: true)
      flash[:notice] = "#{user.nickname}をアクティベートしました"
      redirect_to users_path
    end

    def destroy
      user = User.find(params[:user_id])
      authorize user
      user.update(activated: false)
      flash[:notice] = "#{user.nickname}のアクティベートを解除しました"
      redirect_to users_path
    end
  end
end

app/controllers/users/fetch_mattermost_ids_controller.rb
module Users
  class FetchMattermostIdsController < ApplicationController
    require 'mattermost'
    skip_after_action :verify_authorized

    def create
      @user = User.find(current_user.id)
      uri = URI.parse('https://chat.runteq.jp')
      client = Mattermost.new_client(uri)
      client.login(params[:email], params[:password])
      username = client.get_me['username']
      @user.update(mattermost_id: username) if username.present?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find_by(id: params['id'])
    authorize @user
  end

  def edit
    @user = User.find_by(id: params['id'])
    authorize @user
  end

  def update
    user = User.find_by(id: params['id'])
    authorize user
    user.update(user_params)
    redirect_to users_path
  end

  def destroy
    user = User.find_by(id: params['id'])
    authorize user
    user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :mattermost_id, :activated, :role)
  end
end

app/views/users/edit.html.erb
<section>
  <div class="container py-5 h-100 w-50">
    <div class="card">
      <div class="card-body p-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h5 class="mb-0">ユーザー情報編集</h5>
        </div>
        <hr class="mt-0 mb-4">
        <%= form_with model: @user do |f| %>
          <% if @user.errors.any? %>
            <div class="alert alert-danger mt-2" role="alert">
              <ul class="mb-0 list-inline">
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row pt-1">
            <div class="mb-3">
              <%= f.label :nickname, class: "form-label" %>
              <%= f.text_field :nickname, class: "form-control" %>
            </div>
          </div>
          <div class="row pt-1">
            <div class="mb-3">
              <%= f.label :mattermost_id, class: "form-label" %>
              <%= f.text_field :mattermost_id, class: "form-control" %>
            </div>
          </div>
          <div class="row pt-1">
            <div class="mb-3">
              <%= f.label :activated, class: "form-label" %>
              <%= f.select :activated, [['アクティベート済み', true], ['アクティベート待ち', false]], {}, class: "form-control" %>
            </div>
          </div>
          <div class="row pt-1">
            <div class="mb-3">
              <%= f.label :role, class: "form-label" %>
              <%= f.select :role, User.roles.keys.map{ |key| [t("activerecord.enums.user.role.#{key}"), key] }, { selected: @user.role }, class: "form-control" %>
            </div>
          </div>
          <%= f.submit nil, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr class="text-center">
        <th scope="col"><%= User.human_attribute_name(:id) %></th>
        <th scope="col"><%= User.human_attribute_name(:nickname) %></th>
        <th scope="col"><%= User.human_attribute_name(:github_id) %></th>
        <th scope="col"><%= User.human_attribute_name(:mattermost_id) %></th>
        <th scope="col"><%= User.human_attribute_name(:activated) %></th>
        <th scope="col"><%= User.human_attribute_name(:role) %></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="align-middle text-center">
          <th scope="row"><%= user.id %></th>
          <td class="col"><%= user.nickname %></td>
          <td class="col"><%= user.github_id %></td>
          <td class="col"><%= user.mattermost_id %></td>
          <td class="col-3"><%= user.activated? ? 'アクティベート済み' : 'アクティベート待ち' %></td>
          <td class="col-2"><%= t "activerecord.enums.user.role.#{user.role}" %></td>
          <td class="col"><%= link_to "編集", edit_user_path(user), class: "btn btn-success ml-2" %></td>
          <% if user.activated? %>
            <td class="col">
              <%= link_to user_activate_path(user), data: { turbo_method: :delete } do %>
                <i class="bi bi-unlock-fill h4 text-success"></i>
              <% end %>
            </td>
          <% else %>
            <td class="col">
              <%= link_to user_activate_path(user), data: { turbo_method: :post } do %>
                <i class="bi bi-lock-fill h4 text-danger"></i>
              <% end %>
            </td>
          <% end %>
        <tr>
      <% end %>
      </tr>
    </tbody>
  </table>
</div>