config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#home"

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "logout" => "user_sessions#destroy", :as => :logout
  resource :profile, only: [:show, :edit, :update, :destroy]
  resources :review_requests, only: [:index, :new, :create]
  resources :groups do
    resources :group_members, only: [:create, :destroy], as: :members
  end
  resources :group_member_forms, only: [:create, :destroy]
  resources :users do
    resource :activate, only: [:create, :destroy], module: :users
  end
  resource :fetch_mattermost_id, only: [:create], module: :users
  resource :join_groups, only: [:new, :create, :destroy]
end

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Coreview', root_path, class: "navbar-brand h1" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <%= link_to auth_at_provider_path(:provider => :github), class: 'text-decoration-none' do %>
          <div class="d-flex align-items-center text-black">
            <i class="bi bi-github h3"></i>
            <span class="h5 ms-2 text-bold"><strong>GitHubでログイン</strong></span>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Coreview', review_requests_path, class: "navbar-brand h1" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-house-gear h2"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><%= link_to 'レビュー依頼', review_requests_path, class: "dropdown-item" %></li>
            <li><%= link_to 'グループ一覧', new_join_groups_path, class: "dropdown-item" %></li>
            <li><%= link_to 'マイページ', profile_path, class: "dropdown-item" %></li>
            <% if current_user.admin? %>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'グループ管理', groups_path, class: "dropdown-item" %></li>
              <li><%= link_to 'ユーザー管理', users_path, class: "dropdown-item" %></li>
            <% end %>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>